FROM nginx:alpine

MAINTAINER Diogo Oliveira Mascarenhas <diogomascarenha@gmail.com>

ADD ./.docker/nginx/nginx.conf /etc/nginx/
COPY ./.docker/nginx/sites/*.conf /etc/nginx/sites-available/

ARG PHP_UPSTREAM=php-fpm

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash -G www-data www-data \
    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80 443
